-- ============================================================================
-- STUDENT RETENTION & ATTRITION ANALYSIS SYSTEM
-- Run this whole file once in the Supabase SQL editor (Project > SQL Editor).
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- ENUMS
-- ---------------------------------------------------------------------------
create type user_role as enum ('registrar', 'career_guidance', 'president');
create type enrollment_status as enum ('enrolled', 'graduated', 'dropped', 'shifted');
create type semester_type as enum ('1st', '2nd', 'summer');
create type case_status as enum ('pending', 'investigating', 'resolved');
create type case_type as enum ('dropout', 'shifted');
create type visit_outcome as enum ('re_enrolled', 'confirmed_dropout', 'confirmed_transfer_school', 'unreachable', 'other');

-- ---------------------------------------------------------------------------
-- PROFILES  (one row per auth.users row, created on signup via trigger below)
-- ---------------------------------------------------------------------------
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role user_role not null,
  created_at timestamptz not null default now()
);

-- Auto-create a profile row when someone signs up. Role/full_name are passed
-- in via the signup call's `options.data` (see src/lib/supabase.ts signUp()).
create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Unnamed User'),
    coalesce((new.raw_user_meta_data->>'role')::user_role, 'registrar')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Helper used throughout RLS policies
create or replace function auth_role()
returns user_role as $$
  select role from public.profiles where id = auth.uid();
$$ language sql stable security definer;

-- ---------------------------------------------------------------------------
-- PROGRAMS / COURSES
-- ---------------------------------------------------------------------------
create table programs (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- SCHOOL TERMS  (term_order drives the "what came before this term" logic)
-- ---------------------------------------------------------------------------
create table school_terms (
  id uuid primary key default gen_random_uuid(),
  school_year text not null,        -- e.g. '2025-2026'
  semester semester_type not null,
  term_order int not null unique,   -- 1, 2, 3 ... strictly increasing, chronological
  is_closed boolean not null default false, -- true once detect_enrollment_changes has run for it
  created_at timestamptz not null default now(),
  unique (school_year, semester)
);

-- ---------------------------------------------------------------------------
-- STUDENTS
-- ---------------------------------------------------------------------------
create table students (
  id uuid primary key default gen_random_uuid(),
  student_no text unique not null,
  first_name text not null,
  last_name text not null,
  contact_number text,
  address text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- ENROLLMENTS  (one row per student per term)
-- ---------------------------------------------------------------------------
create table enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  program_id uuid not null references programs(id),
  term_id uuid not null references school_terms(id),
  year_level int not null,
  status enrollment_status not null default 'enrolled',
  created_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  unique (student_id, term_id)
);

create index on enrollments (term_id);
create index on enrollments (program_id);
create index on enrollments (student_id);

-- ---------------------------------------------------------------------------
-- STUDENT CASES  (auto-generated by detect_enrollment_changes)
-- ---------------------------------------------------------------------------
create table student_cases (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  last_enrollment_id uuid references enrollments(id),
  case_type case_type not null,
  from_program_id uuid references programs(id),
  to_program_id uuid references programs(id),   -- only set when case_type = 'shifted'
  status case_status not null default 'pending',
  assigned_to uuid references profiles(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index on student_cases (case_type);
create index on student_cases (status);

-- ---------------------------------------------------------------------------
-- FOLLOW-UP VISITS  (career guidance house-to-house visit log)
-- ---------------------------------------------------------------------------
create table follow_up_visits (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references student_cases(id) on delete cascade,
  visited_by uuid references profiles(id),
  visit_date date not null default current_date,
  reason_category text,   -- financial, health, distance, family, working, not_interested, transferred_school, other
  reason_notes text,
  outcome visit_outcome,
  created_at timestamptz not null default now()
);

create index on follow_up_visits (case_id);

-- ---------------------------------------------------------------------------
-- DETECTION FUNCTION
-- Call this after the registrar has finished entering a term's enrollments.
-- Compares the given term against the immediately preceding term_order and
-- inserts dropout / shifted cases for students who vanished or changed program.
-- ---------------------------------------------------------------------------
create or replace function detect_enrollment_changes(p_term_id uuid)
returns table (dropout_count int, shifted_count int) as $$
declare
  v_current_order int;
  v_prev_term_id uuid;
  v_dropout_count int := 0;
  v_shifted_count int := 0;
begin
  select term_order into v_current_order from school_terms where id = p_term_id;
  if v_current_order is null then
    raise exception 'Unknown term_id %', p_term_id;
  end if;

  select id into v_prev_term_id from school_terms where term_order = v_current_order - 1;

  if v_prev_term_id is not null then
    -- DROPOUT: enrolled previous term, absent this term, not already a case
    with new_dropouts as (
      insert into student_cases (student_id, last_enrollment_id, case_type, from_program_id, status)
      select pe.student_id, pe.id, 'dropout', pe.program_id, 'pending'
      from enrollments pe
      where pe.term_id = v_prev_term_id
        and pe.status = 'enrolled'
        and not exists (select 1 from enrollments ce where ce.student_id = pe.student_id and ce.term_id = p_term_id)
        and not exists (select 1 from student_cases sc where sc.last_enrollment_id = pe.id)
      returning 1
    )
    select count(*) into v_dropout_count from new_dropouts;

    -- SHIFTED: enrolled previous term, enrolled this term under a different program
    with new_shifts as (
      insert into student_cases (student_id, last_enrollment_id, case_type, from_program_id, to_program_id, status)
      select pe.student_id, pe.id, 'shifted', pe.program_id, ce.program_id, 'pending'
      from enrollments pe
      join enrollments ce on ce.student_id = pe.student_id and ce.term_id = p_term_id
      where pe.term_id = v_prev_term_id
        and pe.status = 'enrolled'
        and ce.program_id <> pe.program_id
        and not exists (select 1 from student_cases sc where sc.last_enrollment_id = pe.id)
      returning 1
    )
    select count(*) into v_shifted_count from new_shifts;
  end if;

  update school_terms set is_closed = true where id = p_term_id;

  return query select v_dropout_count, v_shifted_count;
end;
$$ language plpgsql security definer;

-- ---------------------------------------------------------------------------
-- ANALYTICS VIEWS  (used by the President dashboard)
-- ---------------------------------------------------------------------------

-- Enrollment headcount per program per term
create or replace view program_term_stats as
select
  t.id as term_id, t.school_year, t.semester, t.term_order,
  p.id as program_id, p.name as program_name, p.code as program_code,
  count(*) filter (where e.status = 'enrolled') as enrolled_count
from enrollments e
join programs p on p.id = e.program_id
join school_terms t on t.id = e.term_id
group by t.id, t.school_year, t.semester, t.term_order, p.id, p.name, p.code
order by t.term_order, p.name;

-- Term-over-term retention/dropout/shift rate, school-wide and per program
create or replace view retention_rates as
select
  t.id as term_id, t.school_year, t.semester, t.term_order,
  p.id as program_id, p.name as program_name,
  count(*) filter (where sc.id is null) as retained_count,
  count(*) filter (where sc.case_type = 'dropout') as dropout_count,
  count(*) filter (where sc.case_type = 'shifted') as shifted_count,
  count(*) as prior_cohort_size
from enrollments pe
join school_terms t on t.id = pe.term_id
join programs p on p.id = pe.program_id
left join student_cases sc on sc.last_enrollment_id = pe.id
where pe.status = 'enrolled'
group by t.id, t.school_year, t.semester, t.term_order, p.id, p.name
order by t.term_order, p.name;

-- Full case detail, joined for the UI (career guidance + president)
create or replace view case_details as
select
  sc.id, sc.case_type, sc.status, sc.created_at, sc.resolved_at, sc.assigned_to,
  s.id as student_id, s.student_no, s.first_name, s.last_name, s.contact_number, s.address,
  fp.name as from_program_name, tp.name as to_program_name,
  t.school_year, t.semester,
  fv.reason_category, fv.reason_notes, fv.outcome, fv.visit_date
from student_cases sc
join students s on s.id = sc.student_id
join enrollments e on e.id = sc.last_enrollment_id
join school_terms t on t.id = e.term_id
left join programs fp on fp.id = sc.from_program_id
left join programs tp on tp.id = sc.to_program_id
left join lateral (
  select * from follow_up_visits v where v.case_id = sc.id order by v.visit_date desc limit 1
) fv on true;

-- Dropout reasons breakdown (for president charts)
create or replace view dropout_reasons_summary as
select reason_category, count(*) as total
from follow_up_visits
where reason_category is not null
group by reason_category
order by total desc;

-- ---------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
alter table profiles enable row level security;
alter table programs enable row level security;
alter table school_terms enable row level security;
alter table students enable row level security;
alter table enrollments enable row level security;
alter table student_cases enable row level security;
alter table follow_up_visits enable row level security;

-- profiles: everyone can read all profiles (needed to show "assigned to" names); only self can update own row
create policy "profiles_select_all" on profiles for select using (auth.uid() is not null);
create policy "profiles_update_own" on profiles for update using (id = auth.uid());

-- programs / school_terms: readable by all signed-in users; writable by registrar & president
create policy "programs_select" on programs for select using (auth.uid() is not null);
create policy "programs_write" on programs for insert with check (auth_role() in ('registrar','president'));
create policy "programs_update" on programs for update using (auth_role() in ('registrar','president'));

create policy "terms_select" on school_terms for select using (auth.uid() is not null);
create policy "terms_write" on school_terms for insert with check (auth_role() in ('registrar','president'));
create policy "terms_update" on school_terms for update using (auth_role() in ('registrar','president'));

-- students: readable by all signed-in users; writable by registrar
create policy "students_select" on students for select using (auth.uid() is not null);
create policy "students_insert" on students for insert with check (auth_role() = 'registrar');
create policy "students_update" on students for update using (auth_role() = 'registrar');

-- enrollments: readable by all signed-in users; writable by registrar
create policy "enrollments_select" on enrollments for select using (auth.uid() is not null);
create policy "enrollments_insert" on enrollments for insert with check (auth_role() = 'registrar');
create policy "enrollments_update" on enrollments for update using (auth_role() = 'registrar');

-- student_cases: readable by all; only career_guidance/president can update (assign/resolve)
create policy "cases_select" on student_cases for select using (auth.uid() is not null);
create policy "cases_update" on student_cases for update using (auth_role() in ('career_guidance','president'));

-- follow_up_visits: readable by all; only career_guidance can insert; author can update own entries
create policy "visits_select" on follow_up_visits for select using (auth.uid() is not null);
create policy "visits_insert" on follow_up_visits for insert with check (auth_role() = 'career_guidance');
create policy "visits_update" on follow_up_visits for update using (visited_by = auth.uid());

-- ---------------------------------------------------------------------------
-- SEED DATA (optional — comment out if you want to start empty)
-- ---------------------------------------------------------------------------
insert into programs (code, name) values
  ('BSIT', 'BS Information Technology'),
  ('BSCS', 'BS Computer Science'),
  ('BEED', 'Bachelor of Elementary Education'),
  ('BSHM', 'BS Hospitality Management')
on conflict do nothing;

insert into school_terms (school_year, semester, term_order) values
  ('2025-2026', '1st', 1),
  ('2025-2026', '2nd', 2)
on conflict do nothing;
